version: latest

services:
  minio:
    image: minio/minio:RELEASE.2022-07-17T15-43-14Z
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ACCESS_KEY=ACCESS_KEY_DUMMY # 最低3文字
      - MINIO_SECRET_KEY=SECRET_KEY_DUMMY # 最低8文字
  dynamodb-local:
    image: amazon/dynamodb-local:1.18.0
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath .
    ports:
      - 8000:8000
